# Generated by Django 5.0 on 2023-12-26 13:40

import apps.users.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Баланс')),
                ('avatar', models.ImageField(blank=True, default='user/avatar/default_avatar.png', upload_to='user/avatar', verbose_name='Аватар')),
                ('mail_confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('phone_confirmed', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('user_type', models.CharField(blank=True, choices=[('User', 'Пользователь'), ('Agent', 'Агент'), ('Agency', 'Агентство')], max_length=50, null=True, verbose_name='Тип пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.users.manager.UserManager()),
            ],
        ),
    ]
